# Site
name: 'Stewart Watkins Portfolio'
description: 'My most recent projects'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: '/stewart-watkins-portfolio'
disqus: 'demowebsite'
email: 'stewartwatkins@gmail.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
subtitle: 'site tagline that appears below site title in masthead'

include: ["_pages"]
permalink: /:title/



# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    stew:
      name:           Stew
      site:           https://www.wowthemes.net
      avatar:         /assets/images/my_pic.JPG
      bio:            "Hi, I am Stew, a freelance data analyst!"
      email:          stewartwatkins@gmail.com
      twitter:        https://twitter.com/wowthemesnet
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
